### ISSUE TITLE
have no method to hide the tabbar

### ISSUE THREAD

**Issue by lenvonsam** [Edig/TTTabBar#1]
i can not hide tabbar when push to next controller

**Comment by Edig** [comment]
Hi levonsam, I do it this way

Edit: I just update the code with the newest I'm using that has this function

In my class that has "TTTabBar" I create two notifications

```
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "hideTab", name: "hideTab", object: nil)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "showTab", name: "showTab", object: nil)

func hideTab() {
    self.hideTabBar(true)
}

func showTab() {
    self.showTabBar(true)
}
```

Note: the true is for animated:

**Comment by Edig** [comment]
Update your code to V1.1.1 (available in cocoapods)

https://github.com/Edig/TTTabBar/releases/tag/1.1.1

**Comment by lenvonsam** [comment]
now this plugin can  hide and show self ,  thx Edig fix this bug
