### ISSUE TITLE
find another bug

### ISSUE THREAD

**Issue by lenvonsam** [Edig/TTTabBar#2]
when choosed one tab,the view controller is presenting correctly, but i press on button in the view controller to push next controller and then i tap another tab ,  and then back to tap choosed tab, the origin view controller in this choose tab is disappear

![image](https://cloud.githubusercontent.com/assets/10168476/11081711/216375d2-885a-11e5-9c2e-aaa73059c3c3.png)

![image](https://cloud.githubusercontent.com/assets/10168476/11081906/b2367306-885b-11e5-9d6e-0322840d5e06.png)

next controller ,
![56](https://cloud.githubusercontent.com/assets/10168476/11081876/7032803a-885b-11e5-88bf-b0f0ff8bdd85.png)

![image](https://cloud.githubusercontent.com/assets/10168476/11081921/e5a2e0da-885b-11e5-8ce8-6c321e9635e7.png)

when i tap the choosed tab at the first time ,the bug is done

![image](https://cloud.githubusercontent.com/assets/10168476/11081958/292c7e38-885c-11e5-87c0-2669abb76f2c.png)

**Comment by Edig** [comment]
I Just try it in my app and works fine, could you post your code?

**Comment by lenvonsam** [comment]
![image](https://cloud.githubusercontent.com/assets/10168476/11086143/f2b0dc96-8888-11e5-9c90-08a9e09a1c3e.png)

![image](https://cloud.githubusercontent.com/assets/10168476/11086167/233c1c36-8889-11e5-820f-1178adee6f3e.png)

the third tab viewController is a navigationController, you can have a try Edig

**Comment by Edig** [comment]
I'm investigating maybe its a memory problem let me try it in my simulator

**Comment by Edig** [comment]
@lenvonsam could you please try checking if you have a memory warning? because I try it in different ways and it juts work fine

**Comment by lenvonsam** [comment]
hi Edig,i use this command rm -rf ~/Library/Developer/Xcode/DerivedData  to remove cache memory, but  it does not work, i mean you push to next controller at the same time tap the first tab icon(do not pop it),and then tap the third tab icon , the origin third view is disappeared , do you have another communication media

**Comment by Edig** [comment]
sure, edig50@gmail.com
