### ISSUE TITLE
how to choose tab manually 

### ISSUE THREAD

**Issue by lenvonsam** [Edig/TTTabBar#4]
Hi Edig:
   Recently, I need choose tab manually not the first tabItem view when the controller present, how to resolve this problem.

the default page:
![image](https://cloud.githubusercontent.com/assets/10168476/11491228/e9f0338a-981a-11e5-97fe-e96cd58375a5.png)

i want the third tab choosed when init tabcontroller present 
![image](https://cloud.githubusercontent.com/assets/10168476/11491242/06ed295c-981b-11e5-8b12-fe159ad65b38.png)

**Comment by Edig** [comment]
Just set `defaultTabBarItem` to the  `TTTabBarItem` that you want to be first

**Comment by lenvonsam** [comment]
how to use it 
can u give me a example
i try it does not work~

![image](https://cloud.githubusercontent.com/assets/10168476/11492584/5a790046-982a-11e5-820b-82faa2634369.png)

**Comment by lenvonsam** [comment]
I have resolved the problem,thx Edig
