### ISSUE TITLE
pod is not synced

### ISSUE THREAD

**Issue by whoshallsucceed** [Edig/TTTabBar#6]
I have been having trouble trying to extend TTTabBar to add custom behaviour. Until I realised it was because of TTTabBar not being `public`.

So I forked TTTabBar and wanted to make the change. Then I noticed the sources are actually what I would like to get in my project.

So, is it me missing something obvious or the pod is not up to date? And would it be possible to sync it with the sources?

**Comment by ionutivan** [comment]
You are right. From the commit tree, the change is there, it's just that a version with that change is not released (so through cocoapods you are not getting the latest commits). Please release a new version.

**Comment by whoshallsucceed** [comment]
@Edig Any way to make it like real soon? :')
